EXCLUDED_KEYWORDS = [
    "LICENCE KEY",
    "LIS-IP",
    "SHIPPING AND HANDLING",
    "CEREBRO",
    "INSTALLATION SERVICES",
    "TRAINING SERVICES",
    "SQL SERVER IOT LICENCE",
    "FORCEP THUMB",
    "REPORTING SRV",
    "LIS CONN",
    "SENDOUT STN",
    "LABEL PRINTER",
    "WORKSTATION HW SMA",
    "65.64",
    "66.64"
]
